# -*- coding: utf-8 -*-
"""Manipulação de arquivos TXT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8XQbmgDdHv364T6D4cTqQABz3pI46Kf
"""

# Criando e gravando dados em um arquivo (considerando  que o arquivo SAIDA.txt
# não exista no caminho atual)
novo_arquivo = open('SAIDA.txt', 'w')
novo_arquivo.write('Aula de manipulação de arquivos em Python...')
novo_arquivo.write('Escrevendo dados em um arquivo')
novo_arquivo.write('\nCriando uma nova linha')
novo_arquivo.close()

# Adicionando linhas ao arquivo SAIDA.txt
novo_arquivo = open('SAIDA.txt', 'a')
novo_arquivo.write('\nIncluindo uma nova linha...')
novo_arquivo.close()

# Lendo dados de um arquivo, linha a linha
arquivo = open('SAIDA.txt', 'r')
for linha in arquivo:
    print(linha)

arquivo.close()

with open('SAIDA.txt', 'r') as arquivo:
  for linha in arquivo:
    print('Obtendo cada palavra da linha...')
    print(linha.split())
    print(linha)

# Lendo dados de um arquivo
arquivo = open('SAIDA.txt', 'r')
conteudo = arquivo.read() #lendo o conteúdo do arquivo como uma string
print('Conteúdo - método read()...')
print(conteudo)
print(type(conteudo))

# Lendo dados de um arquivo
arquivo.seek(0) # Posiciona o ponteiro do arquivo para o início
lista_linhas = arquivo.readlines() #lendo o conteúdo do arquivo como uma lista
print('Linhas como uma lista - método readlines()...')
print(lista_linhas)
print(type(lista_linhas))

# Gravando uma lista em um arquivo
lista = ['\nJoão da Silva', '\nMaria Antonieta', '\nJoaquim Souza']
arquivo = open('SAIDA.txt', 'a')
arquivo.writelines(lista)
arquivo.close()

# Copiando dados de um arquivo para outro:
open('NOVA_SAIDA.txt', 'w').writelines(open('SAIDA.txt', 'r'))