# -*- coding: utf-8 -*-
"""Manipulação de arquivos CSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bthxv5cn8GciOHJhWvQ4tXvlW47WgIOa
"""

# Criando um arquivo CSV e escrevendo conteúdo no mesmo
import csv

with open('saida.csv', 'w') as arquivo:
    writer = csv.writer(arquivo)
    writer.writerow(('RA', 'nome', 'nota'))
    writer.writerow((100, 'João', 70.5))
    writer.writerow((200, 'Maria', 80.00))
    writer.writerow((300, 'José', 100.00))

# Utilizando outro caractere separador: utilizar o parâmetro
# delimiter no método writer

import csv

with open('nova_saida.csv', 'w') as arquivo:
    writer = csv.writer(arquivo, delimiter = ';')
    writer.writerow(('RA', 'nome', 'nota'))
    writer.writerow((100, 'João', 70.5))
    writer.writerow((200, 'Maria', 80.00))
    writer.writerow((300, 'José', 100.00))

# Objeto reader: utilizado para leitura de dados em um arquivo CSV

with open('futebol.csv', 'r') as arquivo:
  reader = csv.reader(arquivo)
  for linha in reader:
    print(linha)

with open('nova_saida.csv', 'r') as arquivo:
  reader = csv.reader(arquivo, delimiter = ';')
  lista = list(reader)
print(lista)

# Imprimindo uma lista com o conteúdo do arquivo
# (omitindo o cabeçalho)

with open('nova_saida.csv', 'r') as arquivo:
  reader = csv.reader(arquivo, delimiter = ';')
  lista = list(reader)

for l in lista[1:]:
  print(l)

# Criando uma lista com o conteúdo do arquivo (omitindo o cabeçalho)

with open('nova_saida.csv', 'r') as arquivo:
  reader = csv.reader(arquivo, delimiter = ';')
  next(reader) #Lê uma linha e incrementa o ponteiro do arquivo para a próxima linha
  lista = list(reader)

for l in lista:
  print(l)