# -*- coding: utf-8 -*-
"""Trabalhando com o Matplotlib  (parte 2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Okpj7Tu14Bo0ZX4a61IGK84yVceDCCON
"""

import pandas as pd
import matplotlib.pyplot as plt

weather = pd.read_csv('https://github.com/alanjones2/dataviz/raw/master/londonweather.csv')

weather.sample(10)

# Obtendo a numeração dos meses avaliados
x_periodo = weather[weather['Year'] == 1957].Month

# Obtendo os dados de temperaturas
y_temperaturas_1957 = weather[weather['Year'] == 1957].Tmax
y_temperaturas_1977 = weather[weather['Year'] == 1977].Tmax
y_temperaturas_1997 = weather[weather['Year'] == 1997].Tmax
y_temperaturas_2017 = weather[weather['Year'] == 2017].Tmax

x_periodo

# Listando os estilos disponíveis para uso pelo pyplot
print(plt.style.available)

plt.rcdefaults()
plt.style.use('classic')
plt.plot(x_periodo, y_temperaturas_1957, marker='o')
plt.annotate('(Tmax=16.2\n em Maio de 1957)', color = 'blue', xy=(5, 16.2), xytext=(6,13), arrowprops=dict(color='purple'))
plt.title("Temperatura durante o Ano de 1957")
plt.ylabel("Temperatura")
plt.xlabel("Meses")
plt.grid();#axis=’both’,’x’ou ’y’

# Incluindo legenda
plt.rcdefaults()
plt.style.use('grayscale')
plt.plot(x_periodo, y_temperaturas_1957, marker='o', label="Tmax em 1957")

plt.annotate('(Tmax=16.2\n em Maio de 1957)', color = 'blue', xy=(5, 16.2), xytext=(6,13), arrowprops=dict(color='purple'))

plt.title("Temperatura durante o Ano de 1957")
plt.ylabel("Temperatura")
plt.xlabel("Meses")
plt.legend();

# Gráfico de barras
plt.rcdefaults()
plt.style.use('classic')
plt.bar(x_periodo, y_temperaturas_1957, label="Tmax em 1957")

plt.annotate('(Tmax=23.6\n em Junho de 1957)', color = 'green', xy=(6, 23), xytext=(1,18), arrowprops=dict(color='red'))

plt.title("Temperatura durante o Ano de 1957")
plt.ylabel("Temperatura")
plt.xlabel("Meses")
plt.grid(axis='y')
plt.legend();

# Gráficos sobrepostos
plt.rcdefaults()

plt.plot(x_periodo, y_temperaturas_1957, label = "Tmax em 1957", marker = 'o')
plt.plot(x_periodo, y_temperaturas_1977, label = "Tmax em 1977", marker = 's')
plt.plot(x_periodo, y_temperaturas_1997, label = "Tmax em 1997", marker = 'h')
plt.plot(x_periodo, y_temperaturas_2017, label = "Tmax em 2017", marker = '*')

plt.title("Controle de Temperatura Máxima dos últimos 60 anos (A cada 20 anos)")
plt.ylabel("Temperatura")
plt.xlabel("Meses")
plt.grid()
plt.xticks([]) # Oculta rótulo x
plt.legend();

# Trabalhando com Subplots
gridsize = (7, 2)
fig = plt.figure(figsize=(9, 6)) #default (6.4, 4.8)
ax1 = plt.subplot2grid(gridsize, (0, 0), colspan=2, rowspan=2) # 1957
ax2 = plt.subplot2grid(gridsize, (3, 0)) # 1977
ax3 = plt.subplot2grid(gridsize, (3, 1)) # 1997
ax4 = plt.subplot2grid(gridsize, (5, 0), colspan=2, rowspan=2) # 2017

ax1.set_title('Temperatura por mês em 1957')
ax1.plot(x_periodo, y_temperaturas_1957, 'gh--')
ax1.set_xlabel('Meses')
ax1.set_ylabel('1957')
ax1.set_xticks(x_periodo)
ax1.grid()

ax2.set_title('Temperatura por mês em 1977')
ax2.plot(x_periodo, y_temperaturas_1977, 'bo--')
ax2.set_xlabel('Meses')
ax2.set_ylabel('1977')
ax2.set_xticks(x_periodo)
ax2.grid()

ax3.set_title('Temperatura por mês em 1997')
ax3.plot(x_periodo, y_temperaturas_1997, 'rs--')
ax3.set_xlabel('Meses')
ax3.set_ylabel('1997')
ax3.set_xticks(x_periodo)
ax3.grid()

ax4.set_title('Temperatura por mês em 2017')
ax4.plot(x_periodo, y_temperaturas_2017, 'm*--')
ax4.set_xlabel('Meses')
ax4.set_ylabel('2017')
ax4.set_xticks(x_periodo)
ax4.grid();