# -*- coding: utf-8 -*-
"""Trabalhando com o Matplotlib  (parte 1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143fXyEP1DyceVPdaScLWTb1M3gRsZ8zY
"""

#Plotando os primeiros gráficos
import matplotlib.pyplot as plt

# Obs: coloque ';' ao final do comando para ocultar informações sobre o objeto criado
plt.plot([2, 5, 10, 8, 1, 6]);

# Criando um gráfico de linhas, com string de
# formatação para cor, marcador e tipo de linha
plt.plot([2, 5, 10, 8, 1, 6], 'r*-');

#Criando gráfico com 4 conjuntos de Dados
x = [1, 2, 3, 4, 5]
y1 = [-3, 2, 6, 2, 1]
y2 = [4, -2, 5, 8, 3]
y3 = [7, 6, 4, 3, 1]
y4 = [1, 2, 3, 4, 5]

plt.plot(x, y1, 'ro--', x, y2, 'bh-.', x, y3, 'g^:', x, y4, 'y>-')
plt.title("Exemplo");

#Recuperando dados de temperatura anual a cada 20 anos
import pandas as pd
import matplotlib.pyplot as plt

weather = pd.read_csv('https://github.com/alanjones2/dataviz/raw/master/londonweather.csv')

weather.head()

# Obtendo a numeração dos meses avaliados
x_periodo = weather[weather['Year'] == 1957].Month

# Obtendo os dados de temperaturas
y_temperaturas_1957 = weather[weather['Year'] == 1957].Tmax
y_temperaturas_1977 = weather[weather['Year'] == 1977].Tmax
y_temperaturas_1997 = weather[weather['Year'] == 1997].Tmax
y_temperaturas_2017 = weather[weather['Year'] == 2017].Tmax

y_temperaturas_2017

plt.plot(x_periodo, y_temperaturas_1957);

plt.plot(x_periodo, y_temperaturas_1957)
plt.title("Temperatura durante o Ano de 1957")
plt.ylabel("Temperatura")
plt.xlabel("Meses");

#Adicionando elementos ao gráfico

plt.plot(x_periodo, y_temperaturas_1957, color='navy', marker='o', linestyle='dashed', linewidth=2, markersize=12)
plt.title("Temperatura durante o Ano de 1957")
plt.ylabel("Temperatura")
plt.xlabel("Meses");

#Acrescentando o GRID

plt.plot(x_periodo, y_temperaturas_1957, color='green', marker='o', linestyle='dashed', linewidth=2, markersize=12)
plt.title("Temperatura durante o Ano de 1957")
plt.ylabel("Temperatura")
plt.xlabel("Meses")
plt.grid() #axis= 'both', 'x' ou 'y'

# Acrescentando uma anotação
plt.plot(x_periodo, y_temperaturas_1957, color='green', marker='o', linestyle='dashed', linewidth=2, markersize=12)
plt.annotate('(Tmax=16.2\n em Maio de 1957)', color = 'blue', xy=(5, 16.2), xytext=(6,13), arrowprops=dict(color='purple'))
plt.title("Temperatura durante o Ano de 1957")
plt.ylabel("Temperatura")
plt.xlabel("Meses")
plt.grid();#axis='both','x' ou 'y'